[package]
name = "udp_listener"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dis-infra-core = { path = "../../dis-infra-core" }
dis-rs = { path = "../../dis-rs" }
tokio = "1.42.0"
toml = "0.8.19"
