[package]
name = "dis_listener"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
gateway-core = { path = "../../gateway-core" }
dis-rs = { path = "../../dis-rs" }
tokio = "1.42.0"
toml = "0.8.19"
