[package]
name = "basic-usage-infra-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
dis-infra-core = { path = "../../dis-infra-core" }
#dis-rs = { path = "../../dis-rs" }
